//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        public Class()
        {
            this.Registrations = new HashSet<Registration>();
        }
    
        public int ClassId { get; set; }
        public int CourseId { get; set; }
        public int LocationId { get; set; }
        public System.DateTime ClassDate { get; set; }
    
        public virtual Cours Cours { get; set; }
        public virtual ICollection<Registration> Registrations { get; set; }
    }
}
